server:
  port: 8080

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productmanagement?serverTimezone=UTC
    username: root
    password: cien2436
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


